<%-- 
    Document   : managerPage
    Created on : May 4, 2014, 4:20:32 PM
    Author     : commy_000
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Orbit Travel Reservation System Website for CSE 305">

        <title>Orbit Travel Reservation &ndash; CSE 305 Project</title>     

        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.4.2/pure.css">
        <link rel="stylesheet" href="css/layouts/side-menu.css">  

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>      
        <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

        <script src="js/ui.js"></script>
        <script src="js/orbitfunction.js"></script>  
    </head>
    <body>
        <div id="layout">

            <div id="menu"></div>

            <div id="main">
                <div class="header">
                    <h1>Welcome, Manager ___!</h1>
                    <h2>manage minions here</h2>
                </div>

                <div class="content">

                    <h2 class="content-subhead">Select a category</h2>


                    <div class="pure-menu pure-menu-open pure-menu-horizontal" id="managerHeaderMenu">
                        <label for="employees" class="pure-radio">                                                
                            <input id="employees" type="radio" name="optionsRadios" value="employees" checked> Employees                                        
                        </label>

                        <label for="flights" class="pure-radio">                                                
                            <input id="flights" type="radio" name="optionsRadios" value="flights"> Flights                                       
                        </label>     

                        <label for="customers" class="pure-radio">                                               
                            <input id="customers" type="radio" name="optionsRadios" value="customers"> Customers                                        
                        </label>
                        
                        <label for="reservations" class="pure-radio">                                               
                            <input id="reservations" type="radio" name="optionsRadios" value="reservations"> Reservations                                        
                        </label>
                        
                        <label for="revenue" class="pure-radio">                                               
                            <input id="revenue" type="radio" name="optionsRadios" value="revenue"> Revenue                                        
                        </label>
                        
                        <label for="salesreport" class="pure-radio">                                               
                            <input id="salesreport" type="radio" name="optionsRadios" value="salesreport"> Sales Report                                        
                        </label>
                        <!--<ul>
                            <li><a href="#" id="btn0" name="btn0">Employees</a></li>
                            <li><a href="#" id="btn1" name="btn1">Flights</a></li>
                            <li><a href="#" id="btn2" name="btn2">Customers</a></li>
                            <li><a href="#" id="btn3" name="btn3">Reservations</a></li>
                            <li><a href="#" id="btn4" name="btn4">Revenue</a></li>
                            <li><a href="#" id="btn5" name="btn5">Sales Report</a></li>
                        </ul>-->
                    </div>
                    <p>
                    
                    <!--
                        - Add, Edit and Delete information for an employee
                        - Produce a comprehensive listing of all flights
                            Produce a list of most active flights
                            
                            Produce a list of all flights for a given airport
                            Produce a list of all flights whose arrival and departure times are on-time/delayed 
                        - Customers
                            Produce a list of all customers who have seats reserved on a given flight
                        - Produce a list of reservations by flight number or by customer name
                        - Produce a summary listing of revenue generated by a particular flight, destination city, or customer
                            Determine which customer representative generated most total revenue
                            Determine which customer generated most total revenue
                        - Obtain a sales report for a particular month
                                
                    -->
                    
                    <form id="managerForm" class="pure-form pure-form-stacked" method="POST" action='signup'> <!-- TODO: add servlet to post to -->
                        <fieldset id="s0">
                            <legend><strong>Employees</strong></legend>
                            
                            <div id="empRadioList">
                                        <label for="add" class="pure-radio">
                                            <input id="add" type="radio" name="empActions" value="add">
                                            Add
                                        </label>
                                        <label for="update" class="pure-radio">
                                            <input id="update" type="radio" name="empActions" value="update">
                                            Update
                                        </label>
                                        <label for="delete" class="pure-radio">
                                            <input id="delete" type="radio" name="empActions" value="delete">
                                            Delete
                                        </label>
                                </div>
                            
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        <!--   Params: add, edit, delete<p> -->
                                        <button class="pure-button-secondary" id="emp-add-button">Add Employee</button>
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                        <table id="employee-data" class="pure-table">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Name</th>
                                                    <th>SSN</th>
                                                    <th>---</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>0000</td>
                                                    <td>Boone</td>
                                                    <td>12301240924</td>
                                                    <td>
                                                        <button class="pure-button-secondary" id="emp-edit-button">Edit</button>
                                                        &nbsp;&nbsp;&nbsp;
                                                        <button class="pure-button-secondary" id="emp-delete-button">Delete</button>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset id="s1">
                            <legend><strong>Flights</strong></legend>
                            
                            <div id="flightRadioList">
                                        <label for="allFlights" class="pure-radio">
                                            <input id="allFlights" type="radio" name="flightActions" value="allFlights">
                                            View all flights
                                        </label>
                                        <label for="flightsForAirport" class="pure-radio">
                                            <input id="flightsForAirport" type="radio" name="flightActions" value="flightsForAirport">
                                            View all flights for airports
                                        </label>
                                        <label for="mostActive" class="pure-radio">
                                            <input id="mostActive" type="radio" name="flightActions" value="mostActive">
                                            View most active flights
                                        </label>
                                        <label for="onTime" class="pure-radio">
                                            <input id="onTime" type="radio" name="flightActions" value="onTime">
                                            View on-time flights
                                        </label>
                                        <label for="delayed" class="pure-radio">
                                            <input id="delayed" type="radio" name="flightActions" value="delayed">
                                            View delayed flights
                                        </label>
                                </div>
                            
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Params: most active flights, most active flights for airport, arrival/departure times on-time/delayed
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                        <table id="flight-data" class="pure-table">
                                            <thead>
                                                <tr>
                                                    <th>qwewrqt</th>
                                                    <th>wwerwwer</th>
                                                    <th>zzzzsd</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>wat</td>
                                                    <td>fdsssss</td>
                                                    <td>2222</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset id="s2">
                            <legend><strong>Customers</strong></legend>
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Params: customers with seats reserved on given flight
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                        <table id="customer-data" class="pure-table">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Name</th>
                                                    <th>Credit card</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>2000</td>
                                                    <td>Barney</td>
                                                    <td>917098092897</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </fieldset>

                        <fieldset id="s3">
                            <legend><strong>Reservations</strong></legend>
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        <!-- Params: by flight num, by customer name<p> -->
                                        Filters: <br>
                                        <div id="res-tab-radio-list">
                                        <label for="reservationByFlightNum" class="pure-radio">
                                            <input id="res-flight-num" type="radio" name="res-search-type" value="0">
                                            List by flight number
                                        </label>
                                        <label for="reservationByCustName" class="pure-radio">
                                            <input id="res-cust-name" type="radio" name="res-search-type" value="1">
                                            List by customer name
                                        </label>
                                        <label for="reservationByAll" class="pure-radio">
                                            <input id="res-all" type="radio" name="res-search-type" value="2">
                                            List all
                                        </label>
                                        </div>
                                        
                                        <!-- display search-specific stuff here depending on what radio button is selected -->
                                        <div class="pure-u-1" id="res-div0">
                                            <br>Enter flight ID and number: <br>
                                            <fieldset class="pure-group">
                                                <input type="text" name="resAirlineID" class="" placeholder="Flight ID">
                                                <input type="text" name="resFlightNo" class="" placeholder="Flight number">
                                            </fieldset>
                                        </div>
                                        
                                        <div class="pure-u-1" id="res-div1">
                                            <br>Enter customer name: <br>
                                            <fieldset class="pure-group">
                                                <input type="text" name="resFirstName" class="" placeholder="First name">
                                                <input type="text" name="resLastName" class="" placeholder="Last name">
                                            </fieldset>
                                        </div>
                                        
                                        <script>
                                            //this feels like terrible coding practice but okay i guess
                                            resTabHideAll(); 
                                            
                                            $("#res-tab-radio-list").click(function(){
                                                if ( $("#res-flight-num").is(":checked") )
                                                    resTabShowByFlightNum()
                                                else if ( $("#res-cust-name").is(":checked") )
                                                    resTabShowByCustName()
                                                else if ( $("#res-all").is(":checked") )
                                                    resTabHideAll(); 
                                            }); 
                                            
                                            //$("#res-all").change(resTabHideAll()); 
                                            //$("#res-flight-num").change(resTabShowByFlightNum()); 
                                            //$("#res-cust-name").change(resTabShowByCustName()); 
                                            
                                            function resTabHideAll() {
                                                $("#res-div0").hide(); 
                                                $("#res-div1").hide(); 
                                            }
                                            
                                            function resTabShowByFlightNum() {
                                                $("#res-div0").show(); 
                                                $("#res-div1").hide(); 
                                            }
                                            
                                            function resTabShowByCustName() {
                                                $("#res-div0").hide(); 
                                                $("#res-div1").show(); 
                                            }
                                        </script>
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                        <table id="reservation-data" class="pure-table">
                                            
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset id="s4">
                            <legend><strong>Revenue</strong></legend>
                            
                            <div id="revRadioList">
                                        <label for="revByFlight" class="pure-radio">
                                            <input id="revByFlight" type="radio" name="revActions" value="revByFlight">
                                            View revenue generated by a particular flight
                                        </label>
                                        <label for="revByDest" class="pure-radio">
                                            <input id="revByDest" type="radio" name="revActions" value="revByDest">
                                            View revenue generated by a particular destination city
                                        </label>
                                        <label for="revByCust" class="pure-radio">
                                            <input id="revByCust" type="radio" name="revActions" value="revByCust">
                                            View revenue generated by a particular customer
                                        </label>
                                        <label for="custRepRev" class="pure-radio">
                                            <input id="custRepRev" type="radio" name="revActions" value="custRepRev">
                                            View customer rep who generated most revenue
                                        </label>
                                        <label for="custRev" class="pure-radio">
                                            <input id="custRev" type="radio" name="revActions" value="custRev">
                                            View customer who generated most revenue
                                        </label>
                                </div>
                            
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Params: revenue generated by particular flight, dest. city, or customer<br>
                                        which customer rep generated most revenue; which customer generated most revenue
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                        <table id="revenue-data" class="pure-table">
                                            
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset id="s5">
                            <legend><strong>Sales Report</strong></legend>
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        <!-- Params: get report for given month (send afterDate, beforeDate)<p> -->
                                        Month start date: <input id="sales-month-afterdate" name='sales-month-afterdate' type="date"><p>
                                        Month end date: <input id="sales-month-beforedate" name='sales-month-beforedate' type="date"><p>
                                            ???
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                        <table id="sales-report-data" class="pure-table">
                                            
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        
                        <div>&nbsp</div>

                        <button type="submit" class="pure-button pure-button-primary">Refresh</button>
                        <span id="signupError" style="color:red">${requestScope.errorMessage}</span>
                    </form>
                    
                    <script>
                        //Control which page displays here
                        numtabs = 6; 
                        displayNum(0); 
                        
                        //onclick="display0"
                        /*for (var a = 0; a < numtabs; a++) {
                            $("#btn" + a).click(function(event) {
                                displayNum(a); 
                            }); 
                        }*/
                         $("#managerHeaderMenu").click(function(){
                            if ( $("#employees").is(":checked") )
                                displayNum(0);
                            else if ( $("#flights").is(":checked") )
                                displayNum(1);
                            else if ( $("#customers").is(":checked") )
                                displayNum(2);
                            else if ( $("#reservations").is(":checked") )
                                displayNum(3);
                            else if ( $("#revenue").is(":checked") )
                                displayNum(4);
                            else if ( $("#salesreport").is(":checked") )
                                displayNum(5);
                          });
                        
                        $("#btn0").click(function(event){
                            displayNum(0); 
                        }); 
                        $("#btn1").click(function(event){
                            displayNum(1);
                        }); 
                        $("#btn2").click(function(event){
                            displayNum(2);
                        }); 
                        $("#btn3").click(function(event){
                            displayNum(3);
                        }); 
                        $("#btn4").click(function(event){
                            displayNum(4);
                        }); 
                        $("#btn5").click(function(event){
                            displayNum(5);
                        }); 
                        
                        function displayNum(num) {
                            $("#s" + num).show(); 
                            for (var i = 0; i < num; i++)
                                $("#s" + i).hide();
                            for (var j = num+1; j < numtabs; j++)
                                $("#s" + j).hide(); 
                        }
    
                        /*function display0() {
                            $("#s0").show(); 
                            $("#s1").hide(); 
                            $("#s2").hide(); 
                            //for (var i = 1; i < numtabs; i++)
                            //    $("#s" + i).hide(); 
                        }
                        
                        function display1() {
                            $("#s1").show(); 
                            $("#s0").hide(); 
                            $("#s2").hide(); 
                            //for (var i = 0; i < 1; i++)
                            //    $("#s" + i).hide();
                            //for (var j = 2; j < numtabs; j++)
                            //    $("#s" + j).hide(); 
                        }
                        
                        function display2() {
                            $("#s2").show(); 
                            $("#s0").hide(); 
                            $("#s1").hide(); 
                            //for (var i = 0; i < 2; i++)
                            //    $("#s" + i).hide();
                            //for (var j = 3; j < numtabs; j++)
                            //    $("#s" + j).hide(); 
                        }*/
                        
                    </script>



                    <h2 class="content-subhead">Project Specification</h2>
                    <p>
                        The basic idea behind your on-line travel reservation system is that it will allow customers to use the web to browse/search the contents of your database (at least that part you want the customer to see) and to make flight reservations over the web. Your web site should allow users to make both domestic and international reservations. It should also allow users to query the database for available flights (direct or indirect) between a pair of cities for a given date and "approximate" time.

                        Your system should also support reverse auction, in which individuals specify the price they are willing to pay for a seat and the airlines either agree to sell it at that price or not. Reverse auction sites include priceline.com and expedia.com, a Microsoft-owned travel site that has a feature enabling customers to name their price.

                        Actual travel sites allow you to do a lot more than simply make flight reservations. For example, you can book a rental car or a hotel room. Due to time limitations, we will stick to flight reservations only this semester.

                        Your database system must be based on the specifications and requirements that follow.     
                    </p>
                </div>
            </div>
        </div>

        <script src="js/ui.js"></script>
    </body>
</html>
