<%-- 
    Document   : managerPage
    Created on : May 4, 2014, 4:20:32 PM
    Author     : commy_000
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Orbit Travel Reservation System Website for CSE 305">

        <title>Orbit Travel Reservation &ndash; CSE 305 Project</title>     

        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.4.2/pure.css">
        <link rel="stylesheet" href="css/layouts/side-menu.css">  

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>      
        <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

        <script src="js/ui.js"></script>
        <script src="js/orbitfunction.js"></script>  
    </head>
    <body>
        <div id="layout">

            <div id="menu"></div>

            <div id="main">
                <div class="header">
                    <h1>Welcome, Manager ___!</h1>
                    <h2>manage minions here</h2>
                </div>

                <div class="content">

                    <h2 class="content-subhead">Select a category</h2>


                    <div class="pure-menu pure-menu-open pure-menu-horizontal" id="managerHeaderMenu">
                        <ul>
                            <li><a href="#" id="btn0">Employees</a></li>
                            <li><a href="#" id="btn1">Flights</a></li>
                            <li><a href="#" id="btn2">Customers</a></li>
                            <li><a href="#">Reservations</a></li>
                            <li><a href="#">Revenue</a></li>
                            <li><a href="#">Sales Report</a></li>
                        </ul>
                    </div>
                    
                    <!--
                        Add, Edit and Delete information for an employee
                        Produce a comprehensive listing of all flights
                            Produce a list of most active flights
                            
                            Produce a list of all flights for a given airport
                            Produce a list of all flights whose arrival and departure times are on-time/delayed 
                        Produce a list of reservations by flight number or by customer name
                        Produce a summary listing of revenue generated by a particular flight, destination city, or customer
                            Determine which customer representative generated most total revenue
                            Determine which customer generated most total revenue
                        Obtain a sales report for a particular month
                                
                        - customers category?
                        Produce a list of all customers who have seats reserved on a given flight        
                    -->
                    
                    <form class="pure-form pure-form-stacked" method="POST" action='signup'> <!-- TODO: add servlet to post to -->
                        <fieldset id="s0">
                            <legend>Employees</legend>
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Params
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset id="s1">
                            <legend>Flights</legend>
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Params
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset id="s2">
                            <legend>Customers</legend>
                            <div class="pure-g-r">

                                <div class="pure-u-1-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Params
                                    </div>
                                </div>

                                <div class="pure-u-3-4">
                                    <div class="pure-u-1 pure-u-med-1-3">
                                        Relevant table
                                    </div>
                                </div>
                            </div>
                        </fieldset>

                        <div>&nbsp</div>

                        <button type="submit" class="pure-button pure-button-primary">Create Account!</button>
                        <span id="signupError" style="color:red">${requestScope.errorMessage}</span>
                    </form>
                    
                    <script>
                        //Control which page displays here
                        numtabs = 3; 
                        displayNum(0); 
                        
                        //onclick="display0"
                        /*for (var a = 0; a < numtabs; a++) {
                            $("#btn" + a).click(function(event) {
                                displayNum(a); 
                            }); 
                        }*/
                        $("#btn0").click(function(event){
                            displayNum(0); 
                        }); 
                        $("#btn1").click(function(event){
                            displayNum(1);
                        }); 
                        $("#btn2").click(function(event){
                            displayNum(2);
                        }); 
                        
                        function displayNum(num) {
                            $("#s" + num).show(); 
                            for (var i = 0; i < num; i++)
                                $("#s" + i).hide();
                            for (var j = num+1; j < numtabs; j++)
                                $("#s" + j).hide(); 
                        }
    
                        /*function display0() {
                            $("#s0").show(); 
                            $("#s1").hide(); 
                            $("#s2").hide(); 
                            //for (var i = 1; i < numtabs; i++)
                            //    $("#s" + i).hide(); 
                        }
                        
                        function display1() {
                            $("#s1").show(); 
                            $("#s0").hide(); 
                            $("#s2").hide(); 
                            //for (var i = 0; i < 1; i++)
                            //    $("#s" + i).hide();
                            //for (var j = 2; j < numtabs; j++)
                            //    $("#s" + j).hide(); 
                        }
                        
                        function display2() {
                            $("#s2").show(); 
                            $("#s0").hide(); 
                            $("#s1").hide(); 
                            //for (var i = 0; i < 2; i++)
                            //    $("#s" + i).hide();
                            //for (var j = 3; j < numtabs; j++)
                            //    $("#s" + j).hide(); 
                        }*/
                        
                    </script>



                    <h2 class="content-subhead">Project Specification</h2>
                    <p>
                        The basic idea behind your on-line travel reservation system is that it will allow customers to use the web to browse/search the contents of your database (at least that part you want the customer to see) and to make flight reservations over the web. Your web site should allow users to make both domestic and international reservations. It should also allow users to query the database for available flights (direct or indirect) between a pair of cities for a given date and "approximate" time.

                        Your system should also support reverse auction, in which individuals specify the price they are willing to pay for a seat and the airlines either agree to sell it at that price or not. Reverse auction sites include priceline.com and expedia.com, a Microsoft-owned travel site that has a feature enabling customers to name their price.

                        Actual travel sites allow you to do a lot more than simply make flight reservations. For example, you can book a rental car or a hotel room. Due to time limitations, we will stick to flight reservations only this semester.

                        Your database system must be based on the specifications and requirements that follow.     
                    </p>
                </div>
            </div>
        </div>

        <script src="js/ui.js"></script>
    </body>
</html>
